version: 2
sources:
  - name: injuries
    schema: raw
    tables:
      - name: raw_injuries
        identifier: _airbyte_raw_minio_injuries
      - name: raw_products
        identifier: _airbyte_raw_minio_products
      # - name: reviews
      #   identifier: raw_reviews 
      #   loaded_at_field: date
      #   freshness:
      #     warn_after: {count: 1, period: hour}
      #     error_after: {count: 24, period: hour}