version: 2
sources:
  - name: injuries
    schema: raw
    tables:
      - name: raw_injuries
        identifier: _airbyte_raw_minio_injuries
      - name: raw_products
        identifier: _airbyte_raw_minio_products
